apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook
  namespace: guestbook
spec:
  host: guestbook.apps.c1.sandbox56.opentlc.com
    targetPort: 80
  to:
    kind: Service
    name: frontend
    weight: 100
